repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.7.2
    hooks:
      - id: golangci-lint

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.1
    hooks:
      - id: terraform_tflint

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: ["--fix", "--ignore", "node_modules", "--ignore", ".gemini", "--ignore", "private"]

  - repo: local
    hooks:
      - id: go-unit-tests
        name: Run Go Unit Tests
        entry: go test ./...
        language: system
        pass_filenames: false
        always_run: true

